// 교사가 승인한 YouTube 채널 목록.
// 추천 영상은 이 목록의 channelId 안에서만 검색한다.
// channelId는 사람이 실제 채널을 확인한 값만 넣는다.

export const APPROVED_YOUTUBE_CHANNELS = [
  {
    name: '국가유산채널(K-Heritage Channel)',
    handle: '',
    searchName: '국가유산채널',
    channelId: 'UCRO-l6Fli7rtpY2O9Y5NIzw',
    tags: ['문화유산', '역사', '사회', '교육'],
    priority: 1,
    note: '한국 문화유산 관련 고품질 교육 콘텐츠 채널',
  },
  {
    name: '국가유산청 Korea Heritage Service',
    handle: '',
    searchName: '국가유산청',
    channelId: 'UCxWZbyZ-UhohFp3BYNh2d7Q',
    tags: ['문화유산', '역사', '사회', '교육'],
    priority: 1,
    note: '국가유산청 공식 유튜브 채널',
  },
  {
    name: '국립중앙박물관',
    handle: '',
    searchName: '국립중앙박물관',
    channelId: 'UC7Pc7sflxGNdgh-ep_jlbEg',
    tags: ['문화유산', '역사', '박물관', '사회', '교육'],
    priority: 1,
    note: '국립중앙박물관 공식 채널',
  },
  {
    name: '국립민속박물관',
    handle: '',
    searchName: '국립민속박물관',
    channelId: 'UCjXHIWPMZPyU3jWN4iz2JEA',
    tags: ['문화유산', '역사', '박물관', '민속', '사회', '교육'],
    priority: 2,
    note: '국립민속박물관 공식 채널',
  },
  {
    name: '국립민속박물관 어린이박물관',
    handle: '',
    searchName: '국립민속박물관어린이박물관',
    channelId: 'UCNAyysJBAuujCNDI5VLLksg',
    tags: ['문화유산', '역사', '박물관', '민속', '초등', '교육'],
    priority: 2,
    note: '어린이 대상 민속·전통문화 교육 콘텐츠 후보',
  },
  {
    name: '국사편찬위원회',
    handle: '',
    searchName: '국사편찬위원회',
    channelId: 'UCFGT4YC0Kzg3yAMAfgJXOxQ',
    tags: ['역사', '한국사', '사료', '사회', '교육'],
    priority: 1,
    note: '국사편찬위원회 공식 유튜브 채널. 검증된 한국사·사료 기반 학습 자료 후보',
  },
  {
    name: '독립기념관',
    handle: '',
    searchName: '독립기념관',
    channelId: 'UCKrhdGv0KuMwFejjCp5JZIg',
    tags: ['역사', '독립운동', '근현대사', '사회', '교육'],
    priority: 1,
    note: '독립기념관 공식 채널. 독립운동사와 근현대사 교육 콘텐츠 후보',
  },
  {
    name: '독립기념관 배움상자',
    handle: '',
    searchName: '독립기념관 배움상자',
    channelId: 'UCfWLVL4iLppHd5uqpVjCtmg',
    tags: ['역사', '독립운동', '근현대사', '초등', '교육'],
    priority: 2,
    note: '독립기념관 교육용 배움상자 관련 콘텐츠 후보',
  },
  {
    name: '한국학중앙연구원',
    handle: '',
    searchName: '한국학중앙연구원',
    channelId: 'UCuQTqOmCbyib_BhfkfKSfLg',
    tags: ['역사', '한국학', '문화유산', '전통문화', '교육'],
    priority: 2,
    note: '한국학중앙연구원 공식 채널',
  },
  {
    name: '한국학중앙연구원 호기심왕국',
    handle: '',
    searchName: '한국학중앙연구원 호기심왕국',
    channelId: 'UCL_ze51Avh0E-nhpJ6Xd2jA',
    tags: ['역사', '한국학', '문화유산', '전통문화', '교육'],
    priority: 2,
    note: '한국학을 쉽게 풀어주는 지식형 콘텐츠 후보',
  },
  {
    name: '동북아역사재단',
    handle: '',
    searchName: '동북아역사재단',
    channelId: 'UCN5IL-Q6rIyusGDSDr8AaCA',
    tags: ['역사', '동북아', '독도', '고대사', '사회', '교육'],
    priority: 2,
    note: '동북아역사재단 공식 채널. 독도·고구려·발해 등 동북아 역사 주제 후보',
  },
  {
    name: '동북아역사재단 독도체험관',
    handle: '',
    searchName: '동북아역사재단독도체험관',
    channelId: 'UC29T_nRqD62_CH8exrxUnUg',
    tags: ['역사', '동북아', '독도', '사회', '교육'],
    priority: 2,
    note: '독도 관련 교육 콘텐츠 후보',
  },
  {
    name: '대한민국역사박물관',
    handle: '',
    searchName: '대한민국역사박물관',
    channelId: 'UCqGo34xpxp6LPPpSgCsslSg',
    tags: ['역사', '근현대사', '박물관', '사회', '교육'],
    priority: 1,
    note: '대한민국역사박물관 공식 채널. 근현대사 전시·교육 콘텐츠 후보',
  },
  {
    name: '전쟁기념사업회',
    handle: '',
    searchName: '전쟁기념사업회',
    channelId: 'UClEbJ_3EMk26pJ3Qun7QRMw',
    tags: ['역사', '전쟁사', '호국', '근현대사', '사회', '교육'],
    priority: 2,
    note: '전쟁기념관 관련 공식 전쟁·군사 역사 콘텐츠 후보',
  },
  {
    name: '전쟁기념관 교육·소식',
    handle: '',
    searchName: '전쟁기념관 교육·소식',
    channelId: 'UCI9OQNro-KDVExbiZp3eOEg',
    tags: ['역사', '전쟁사', '호국', '근현대사', '초등', '교육'],
    priority: 2,
    note: '전쟁기념관 교육·소식 채널',
  },
  {
    name: 'EBS 다큐',
    handle: '',
    searchName: 'EBSDocumentary EBS 다큐',
    channelId: 'UCFCtZJTuJhE18k8IXwmXTYQ',
    tags: ['교육', '사회', '역사', '과학', '다큐'],
    priority: 2,
    note: 'EBS 공식 다큐멘터리 채널',
  },
  {
    name: 'EBS 컬렉션 - 사이언스',
    handle: '',
    searchName: 'EBS 컬렉션 사이언스',
    channelId: 'UCiFYUP4_TI70yCkkVJAlxoA',
    tags: ['교육', '과학', '초등'],
    priority: 1,
    note: 'EBS 공식 사이언스 채널. 과학 주제 추천 후보',
  },
  {
    name: 'EBS 지식',
    handle: '',
    searchName: 'EBS 지식',
    channelId: 'UCuuA38hvvuipqXFIP3BfLEA',
    tags: ['교육', '사회', '역사', '과학', '지식'],
    priority: 2,
    note: 'EBS 지식·강연 콘텐츠 채널',
  },
  {
    name: 'EBS',
    handle: '',
    searchName: 'EBS',
    channelId: 'UC-swf20n5xdKW0waeLpXPFQ',
    tags: ['교육', '초등', '사회', '과학', '역사'],
    priority: 3,
    note: 'EBS 공식 유튜브 채널',
  },
  {
    name: 'KBS 다큐',
    handle: '',
    searchName: 'KBS 다큐',
    channelId: 'UC4LW3sOslC14Vn5bcoNUBkg',
    tags: ['교육', '사회', '역사', '과학', '다큐'],
    priority: 2,
    note: 'KBS 다큐 공식 채널',
  },
  {
    name: 'KBS 히스토리',
    handle: '',
    searchName: 'KBS 히스토리',
    channelId: 'UCjPqSbyqm5IZEoXu7I-KPag',
    tags: ['교육', '역사', '한국사', '사회'],
    priority: 1,
    note: 'KBS 역사 콘텐츠 공식 채널',
  },
  {
    name: '국립과천과학관',
    handle: '',
    searchName: '국립과천과학관',
    channelId: 'UCWnC1rQyetvJ29Qjt2mQpoA',
    tags: ['과학', '교육', '초등'],
    priority: 1,
    note: '국립과천과학관 공식 유튜브 채널',
  },
  {
    name: '국립생태원',
    handle: '',
    searchName: '국립생태원',
    channelId: 'UCbl0zikxXmKC_RsEFPbCR4Q',
    tags: ['과학', '생태', '환경', '교육'],
    priority: 1,
    note: '국립생태원 공식 유튜브 채널',
  },
  {
    name: '한국교육학술정보원(KERIS)',
    handle: '',
    searchName: 'KERIS 한국교육학술정보원',
    channelId: 'UCygQeI6WHN8JuSfIc5S7YyA',
    tags: ['교육', '디지털', '사회'],
    priority: 3,
    note: '한국교육학술정보원 공식 채널',
  },
];

export function getActiveApprovedYoutubeChannels() {
  const seen = new Set();

  return APPROVED_YOUTUBE_CHANNELS.filter(channel => {
    const isValid =
      typeof channel.channelId === 'string' &&
      channel.channelId.startsWith('UC');

    if (!isValid || seen.has(channel.channelId)) return false;

    seen.add(channel.channelId);
    return true;
  });
}
